print('=======   Desafio 11   =======')
dolar = float(input('Digite o valor atual do Dolar: US$ '))
euro = float(input('Digite o valor atual do Euro: EUR$ '))
dolarc = float(input('Digite o valor atual do Dolar Canadense: CAD$ '))
real = float(input('Quanto de dinheiro você tem na carteira? R$ '))
print('Com o valor de R${} você pode comprar:'.format(real))
print('Dolar US$ {:.2f}'.format((real / dolar)))
print('Euro EUR$ {:.2f}'.format((real / euro)))
print('Dolar Canadense CAD$ {:.2f}'.format((real / dolarc)))
